name: ez_eat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.5.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6
  rive: ^0.13.12
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.0
  go_router: ^14.2.2
  dartz: ^0.10.1
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  image_picker: ^1.0.2
  get_it: ^7.7.0
  firebase_auth: ^5.1.4
  firebase_messaging: ^15.0.4
  shimmer: ^3.0.0
  flutter_stripe: ^11.0.0
  flutter_stripe_web: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^6.0.0
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  animate_do: ^3.3.4
  animations: ^2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/background/
    - assets/images/rive/
    - assets/images/onboarding/
    - assets/images/payment/
    - assets/

